def test_fail(a: float = 1):
    """function failing with an exception"""
    raise RuntimeError
